#!/bin/bash
# Script to test and show data that will appear in dashboard tabs

echo "🧪 Testing Dashboard Tabs Data"
echo "================================"
echo ""

# Database connection
DB_NAME="polymarket_trader"
DB_USER="iabadvisors"

echo "📊 Checking data counts for each tab:"
echo ""
psql -U $DB_USER -d $DB_NAME -c "
SELECT 
  'Markets Tab' as tab_name,
  COUNT(*) as count,
  'Live from Polymarket API' as data_source
FROM markets
UNION ALL
SELECT 
  'Predictions Tab' as tab_name,
  COUNT(*) as count,
  'Generated by ML models' as data_source
FROM predictions
UNION ALL
SELECT 
  'Signals Tab' as tab_name,
  COUNT(*) as count,
  'Auto-generated from predictions' as data_source
FROM signals
UNION ALL
SELECT 
  'Trades Tab' as tab_name,
  COUNT(*) as count,
  'Created from signals (with --auto-trades)' as data_source
FROM trades
UNION ALL
SELECT 
  'Portfolio Tab' as tab_name,
  COUNT(*) as count,
  'Generated from trades' as data_source
FROM portfolio_snapshots;
"

echo ""
echo "📋 Sample Predictions Data:"
echo ""
psql -U $DB_USER -d $DB_NAME -c "
SELECT 
  LEFT(m.question, 50) as market_question,
  ROUND(p.model_probability::numeric, 4) as ai_prediction,
  ROUND(p.market_price::numeric, 4) as market_price,
  ROUND(p.edge::numeric, 4) as edge,
  ROUND(p.confidence::numeric, 4) as confidence,
  p.prediction_time
FROM predictions p
JOIN markets m ON p.market_id = m.market_id
ORDER BY p.prediction_time DESC
LIMIT 5;
"

echo ""
echo "✅ Data check complete!"
echo ""
echo "To see this data in the UI:"
echo "1. Start API server: uvicorn src.api.app:app --host 0.0.0.0 --port 8002"
echo "2. Open browser: http://localhost:8002/dashboard"
echo "3. Check each tab - should show data above!"



